stages:
    - name: test
      if: type = pull_request
language:
    - node_js
node_js:
    - '8'
env:
    global:
        - GH_REF: github.com/entrylabs/entryjs.git
        - GH_REPO: https://github.com/entrylabs/entryjs.git
cache:
    yarn: true
    directories:
        - node_modules
jobs:
    include:
        - stage: test
          install:
              - yarn --ignore-engines
          script: yarn test
